server:
  port: 80
####服务网关名称
spring:
  application:
    name: mayikt-gateway
  cloud:
    gateway:
      discovery:
        locator:
          ####开启以服务id去注册中心上获取转发地址
          enabled: false
        ###路由策略
      routes:
        ###路由id
        - id: order
          ####转发http://www.mayikt.com/
          uri: http://www.baidu.com/
          ###匹配规则
          predicates:
            - Path=/mayikt/**
    ### 127.0.0.1/mayikt   转发到http://www.mayikt.com/